# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a7196826c53fa76c6739bcdf3395d0ce21ca73cd2581f200300f315c3a751ea2e795618697e12f416e73026ef9c104d77b5101a4a563012173999edd8d983e3

test:
  secret_key_base: a506105d88cfa77190535cf0ae5b8d02bab13651b24cf27444746e3406e63ebf97363ef691a83e4e8dca819c482a8fd7db0fecb991750f63a77522b2133c4e99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
